### PR TITLE
Changed Readme too include Badge And links to action

### PR DESCRIPTION
**Pull request by Technically-Possible**

### CODE REVIEW

**Comment by LionZXY** [comment]
It is very important to display the status only in the master.
Can we add a new workflow (e.g. publication of releases) which only works in the master and watch it?

**Comment by LionZXY** [comment]
Sorry for bad description of the task :(

**Comment by Technically-Possible** [comment]
it does only follow the master, am I misunderstanding what you mean?

**Comment by LionZXY** [comment]
No. It show last status build for pull request too

**Review by LionZXY — APPROVED** [review]

**Pull request merged**
