### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Technically-Possible**
Add label in readme with github action build status.

### CODE REVIEW

**Review by rougsig — APPROVED** [review]

**Comment by LionZXY** [comment]
May be move in title?
image

**Comment by Technically-Possible** [comment]
> May be move in title?
> image

yep will do

**Comment by LionZXY** [comment]
Please add link to releases/last actions

**Comment by LionZXY** [comment]
Is the status of the master build shown now exactly?

**Comment by Technically-Possible** [comment]
yes

**Comment by Technically-Possible** [comment]
my pc is freaking out will make new PR and changes will be on there

**Pull request closed without merging**
